# Generated by Django 3.2.7 on 2021-09-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=150)),
                ('nomeDaEmpresa', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100)),
                ('telefone', models.IntegerField()),
            ],
        ),
    ]
